Screenshot of ncase.me/trust
Trinomial Cube
http://de.slideshare.net/x28de/connectivist-layers
@algoethik is running a blog parade "AI for common welfare?". I tried to respond to their questions. (Deutsche Version unten)
The "Split Attention Effect" from Cognitive Load Theory demands that an annotation needs to be close to the item it refers to. I wonder if this is still true if the annotation can be reached by a saccadic eye movement.
How does wisdom differ from knowledge? In my understanding, wisdom grows very slowly, and it is often about what is really important, or actually, what is not important.
I bought Clark Quinn's new book about training myths, semi-myths and misconceptions, and I can whole-heartedly recommend this exciting, in-depth, clinical and precise work.
Many people are enthusiastic about the 'Big Picture' attitude. Some even quote Dyson's distinction between birds (who "fly high") and frogs (who "live in the mud").
Why do we hesitate to accept that we have to forward "the time" ? Because it seems that in reality, it is being switched back: sunset is delayed.
I like Mike Caulfield's post "Media Literacy Is About Where To Spend Your Trust. But You Have To Spend It Somewhere." and in particular, the term 'spend'.
When a chord with a 'nonharmonic tone' is played out of context, it sounds awful, but when we hear it as a 'passing tone' or as a 'neighbor tone', we don't notice the dissonance -- because we expect that it will immediately be resolved.
Stephen Downes's big article "Consciousness" is an incredibly rich resource. The greatest takeaway so far was the explanation of the mysterious 'suddenness' through recognition.
I noticed that for me, MOOC 'objectives' such as "Detail how...", "Describe how...", actually inhibit reflections in the sense of: What struck me as susprising or salient or resonating?
If measuring the 'effectiveness' is mainly about traditional criteria such as knowledge content and storing it safely away, it will be very unbalanced. Measuring OERs, by contrast, offers the opportunity to try out and define new criteria.
I was curious how much I would be able to find from existing OERs and how much I would need to create by myself. I was surprised how easy it was to find things.
The spatial and temporal functions of the working memory may be not only be interrelated. Stephen Downes now expressed the idea that they are indeed similar.
What are the most urgent cases where OERs are most desirable? I think it is often graphics, not text.
I liked Wiley's description of the current copyright situation as a trap. Most authors seem to put up with the trap.
Big improvements of think tools are often achieved through rather small differences, such as the "targeted zooming", or now the "semantic text view" of iMapping.
In my view, McGilchrist's "Master" and "Emissary" modes are the mind's equivalent of what bending and stretching are for the body. So we need to understand the 'flexors' and 'extensors' of brain operation.
Jim McGee wrote a great piece on tools and practices. He argues that the ease of getting started with the first 5% is deceptive. I think it is important that we distinguish between "deep thought and collaborative work". Tools for these two coincide only for roughly 5%.
Why can't media be like a conversation? What makes the internet a "polarization factory" of 'us vs. them'? I think the problem is that is has turned too much towards 'push' media.
What will prove as 'distinctively human' and will survive the cognitive automation? I think it is the personal, the individual, the subjective, and this convinced me of Downes's 'personal learning'.
Seven habits make my workflow satisfying. In particular: pull over push, optimized for browse rather than search, and careless capturing but cultivating later.
Why do learners need interactivity? Because watching their peers recognizing helps their own recognizing more than consuming canned resources.
20 interesting goals from a new game can also be used for something entirely different: You can try to find connections between them. E.g., some are similar to others, or impact others in positive or negative ways, seem to include others, or be otherwise related. And thinking about their complex relationships can be too difficult if you only look at a linear list and most of the connections are only in your head. This might be a good opportunity to demonstrate the benefit of a think tool.
My tool is now able to import from/ export to tools that are inspired by Luhmann's famous Zettelkasten. The magic of this was that he allowed for arbitrary branching at every point in his hierarchical numbering scheme,
Does a neural network need domain knowledge? I think artificial ones do, but human ones do not because they use recognition from the beginning.
I understand now better how the "magic" of my tool works: it makes associations tangible. It turns elusive mental relationships into "hands on" experience, and it compensates for the abstractness of some thought links, with a drawn line "at our fingertips".
Comparing two other think tools with my own tool one can say that they are rather suited as the big long-term storage "cupboard" while my own tool is more like the "table" where things are put for a temporary large overview.
The gem of Sousanis' book "Unflattening" was that it does a great job explaining why the right hemisphere mode ("all-at-once") lives from relations: Basically, it argues that the eye is "dancing and darting", i.e. by its saccadic motion (palpation by means of the gaze) it captures only small fragments at a time, and it is our imagination that needs to combine them into vision.
There was the question of what @downes and @gsiemens can do working together, and I don't want to miss this opportunity for an early Christmas wish list :-)  I there is much to be done in the field of machine-supported human recognition.
In today's hangout, both fathers of Connectivism were unanimous in an important issue:  "There is automation that enables choice &amp; human agency &amp; that which doesnt". I think it is important to distinguish between true control and disguised patronization.
What does my PLE need as a minumum? For me, it is not sufficient to have discussions with posts and comments, but I need to see people behind the comments.
Why is the denial of brain lateralization so grim, piqued and emotional?  The very idea that there are different modes, may be unsettling. The complacency that there is just one right way (and of course this is mine) may be threatened. Furthermore, the notion of two hemispheres suggests that the two modes are equitable.
While I have often argued for Cmapping and against simple hierarchical mindmapping, there are benefits that mitigate the inherent problem of such 
nested hierarchies, They may help capturing the structure of a talk while listening.
I had to clear out my workplace. It was quite interesting to revisit the digital and physical traces of so many years. It started with little slips of paper, to capture data from telephone calls or other little notes, piled up in a drawer. They were best simulated by plain text files.
In a very inspiring paper, R. Williams, S. Gumtau and J. Mackness offer much insights about a wide spectrum of the cognitive development. It appears very clear and suggests how all the pieces fit together: From embodied cognition, synesthetic abilities, metaphors, to generalizations and abstractions.
Anthropomorphic speak to communicate about what the computer "knows" or "thinks" can be perfectly ok. But there are problematic areas. One is deep machine learning, where such terms dangerously blur the border between reality and science fiction. Another one is  McGilchrist's "Master and Emissary" for the two brain hemispheres.
I often wanted to share the great experience of using my favorite tool and to show off its condensed overview. Now, a read mode format is available that can be viewed without my tool.
If you stroll around the word roots on my map, you may notice that the category #3, "Space, Position, Form", shows particularly many items in this selection of the top 300 most prolific roots, i.e. the ones that have inspired the most new words. So what does it mean that spatial concepts were so prolific?
The map is great metaphor when thinking about what can be looked up and what needs to be in the brain.  I think the difference is between searching something on a knowledge map, and browsing the map.
I hope that we lab rats produced a sufficient amount of results for the experimentors. I think we did, and in this sense, the experiment should be seen as a success.
In a great summary of much of his work, "My Viva", Stephen Downes addresses some august ideas about knowledge construction -- and topples them off their pedestal. Abstract ideas such as: representations that "stand for" concepts, and propositions "encoding" knowledge, were unchallenged presuppositions. But "recognizing" is the crucial thing.
A great article on the Federated Wiki about the "mode of discourse" captures particularly well the spirit of this endeavor, where conflicting ideas are to be presented without a "Gotcha Moment".
In two great post about the preposition, Keith Hamon argues "The preposition does not signify something other than its coupling." His discussion puts prepositions at one end of the spectrum of words, and farther away from the narrow end of the funnel of language.
Gradually, Stephen Downes' explanation of Knowledge as Recognition becomes more and more lucid. Myself, I most intensively recognized this idea in McGilchrist's description of two different ways of "knowing".
Good news from Cmap: there are now ways to avoid two stubborn behaviors of the application: No more forced proposition texts, and arrow-heads even if arrows slope downwards. But the bad news is that doubleclicking on my cmaps doesn't work any more, so I have to roll back to the old version.
In the last week of the dual (xMOOC and cMOOC) DALMOOC, I can say that I am very satisfied. Mainly this is because the course has fully satisfied the cMOOC criterion that the weeks are independent from one another.
In the #DALMOOC course on Learning Analytics, I encountered a nice application that visualizes these terrible large Moodle forum threads. I hope that, one day, we might have a tool that can also visualize the conceptual connections between the posts.
I am currently enrolled in #DALMOOC, a blend of cMOOC and xMOOC, on a very promising platform.
OK, concepts are no longer transported into the student's brain, but only constructed there. But how does the "construction set" get into the brain?
in a little symposium called "Denkwerkzeug" (= Think Tool), in a charming location right below Frankenstein castle, it became very clear that good tools are still missing. Meantime, there is the occasion of listing my own top 10 tools.
I have often tried to explain my biggest problem with connectivism. Maybe a picture works better. There is the neuronal layer, and then there is the society layer. But how are these related? The metaphor of conceptual connections could be closing the gap.
Why do great visual thinkers still use paper and pen, and forgo the powers of an electronic canvas? Watching Dave Gray in a conversation about interaction design clarified it to me.
I am still wondering if conceptual connections would fulfill one of Stephen Downes' criteria: "A connection exists between two entities when a change of state in one entity can cause or result in a change of state in the second entity." Words can change each other's subtle nuances;  "Language is use",
When I try to understand what "recognition" means, what makes "recognizing" different from just seeing the single parts, I cannot visualize this at the neural level. Rather, I need some imagination from an accessible level -- from the conceptual level.
There is much food for thought in the current controversies around Digital Humanities. I think I recognize the meaning of some comments, but I would not be able to understand them by algorithmic analysis.
Live blogging from a Digital Humanities Workshop ...
An interesting presentation at the DHD 2014 Digital Humanities conference covered different attitudes towards ontologies.
"Measure learning outcomes at the atomic concept level" sounds strange.
Downes explains that representational theories only work if we assume a little "homunculus" inside ourselves. Therefore he emphasises the role of recognition. McGilchrist calls the representational mode an "emissary" who needs to return to his master, the presentational mode, for reintegration.
Not everything interested me sufficiently. But what I did engage with (passively or actively) was indeed extremely worthwhile, inspiring and fulfilling.  So I'd like thank you all.
An interesting post by Keith Lyons about Mathematical elegance inspired my to collate some sources that have intrigued me for quite a while: "Aesthetics as Pre-linguistic Knowledge", intuition vs. visualization/ illustration/ exemplification, and space in soccer.
While a "network" is obviously open ended, I am not sure how the term "community" is usually meant by native speakers of English. For me, the word has many connotations of a close or narrow grouping, with many senses like confraternities or religious fold.
Trying to dive into Deleuze &amp; Guattari, some interesting stuff caught my eyes which aligns well with my understanding of both Connectivism and McGilchrist's book about the Making of the Western World.
Words like "power" and even "weapons" were mentioned strikingly often in the first week of Rhizo14. Are here definitions (see last post) being used for fighting?
For me, the most interesting part of rhizomatic rather than arborescent thinking is, that it allows for networked complex patterns rather than just stubborn rules. However, in the first few days of the Rhizo14 MOOC, I have read the words "rules" and "definition" more often than in months before.
I need to visualize how rhizomatic learning might look like. Beneath the surface, you see how all plants are connected. So if you are interested in one topic, you might need to learn about another one before. Imagine how you would pull out these topics: Just the other way around than in traditional learning.
After the upgrade to Windows 8.1 (taking several hours), I found several annoying problems.
I am unsettled about the word (notion? term? concept?) of "concept". So I looked up more and more entries in the dictionary, and I need to visualize them: Each line is a dictionary entry.
Two Catalan authors see "Three problems with the connectivist conception of learning" and challenge its core ideas. I am not convinced. They seem to have a very different view of patterns than I have (binomial rather than gradually emerging), and of connections (all of strength 1 or 0).
The metaphor of a raft visualizes that concepts are not merely nodes on a concept map, not abstract-symbolic dots or neat circles, but that connections between them play a crucial role.
In the last six weeks I participated in a wonderful course offered by Howard Rheingold: “Think Know Tools”. It was very open in the sense of open minds. And in particular, the diversity component was at least as strong as in (c-)MOOCs.
My first contact with IT was 40 years ago. Spectacular speeds and sizes of storage and transportation of formerly analog carriers, never impressed me. For me, really new empowerment came through rearranging, and sorting and quick grouping. And many of the great novelties ignited hopes that were bigger than the reality emerging later.
My tool is like a cMap tool, plus a notes facility like that of PersonalBrain (plus, of course, many left deficiencies!)
It’s still beta and it’s not beautiful. It’s very difficult to explain why I am so enthusiastic about my tool. The rationalization of its surprising power is roughly, that it minimizes the distance between two operating modes, and minimizes abstraction.
Today’s OLDaily points to a paean of abstraction. I wonder if it is really useful to glorify the abstract in this radical, literal, narrow (well: abstract) sense, or if we are conflating it with other forms of generalizations or indirections, such as patterns or metaphors.
Jenny’s discussion with Howard about the internal resistance against mind mapping, caused me to question my own reasons: why am I convinced that mapping is worth the effort, and why does “linear thinking” sound so deterrent to me? It has to do with constraints.
Compare learning with a Shishi Odoshi. The emergent learning is like the ongoing flow which is typical for the largest part of time, before the tipping point of the seesaw is reached. By contrast, the threshold, or “Ah-ha” moment, is only the short point in time where the spectacular, loud, recognizeable event happens.
Desperately seeking a new mapping tool, because my Powerpoint 2003 won’t work in Windows 8. Read what problems I have with many mind-maps, C-maps, topic-maps and I-maps.
When I wanted to curate a coherent assembly of my old blog posts, I was soon reminded again of Stephen Downes’ explanation: “the problem is that you’re tied to the sign, word and symbol.” I ended up with unnamed clusters of tags, because the interesting concepts lie between these tags, in the connections.
With concept maps, “the problem is that you’re tied to the sign, word and symbol.” (Stephen). So I am still grappling with the connections between (or within, or “beyond”?) concepts. Unlike Cmaps, the brain is not filled with propositions. But perhaps we should simply let go the traditional roles of nodes and connector lines, and find the ideas in sets of connectors?
Downes’ new book on connective knowledge tells a lot about knowledge that you cannot read anywhere else. My recommendations for a rhizomatic journey through the book include 5 sections as starting points.
One of the main obstacles against one sense of openness is another sense of openness: In traditional peer reviewed journals, peers are open in ONE sense when they frankly give negative feedback. Of course this excludes openness in the OTHER sense, the sense of public accessibiity.
In this week’s article I recognized my “selves” #3 and #4 (participatory and asynchronous). But while Bonnie looks “beyond the traces and trails we leave behind”, I am still grappling with the effect of the sheer mass of such traces.
Week 33 Task 4.
While the publicity of the term “MOOC” is rapidly increasing, also the danger is growing that its original meaning and principles will be watered down. Everyone can call their endeavour a MOOC, no matter how much they are actually willing to let go their “controletti mentality”. But we must bear that it’s uncertain whose definition of MOOC will stick.
I found it difficult to understand the idea of knowledge of a community. It helped me to think of a community of experts, of becoming like one, and of the continuum of actefacts exchanged among them.
On the new MOOC “Connectivism and Connective Knowledge” (CCK12), there seems to be an exercise for our “crap detector” going on (I like this term by @hrheingold): In today’s Daily, there were two big mistakes aggregated from the same author — at least two, then I skipped him.
Do open space participants either consent or vote with their feet/ walk away? If the open space is a group, this is probably true. In a network, it is different.
In the beginning, connectivism was considered on three layers: neural, conceptual, and social/ external. What has become of the former two layers? For me this is a problem because I cannot grasp that societal knowledge is similarly residing in connections as individual knowledge.
Remix of links and quotations about happiness and learning as by-products, and induction vs. transmission.
Connectivism talks about conceptual connections of varying strength, and learning involves gradually strengthening connections. I visualize these slowly growing connections like ridges emerging from the ground, and I think the time lapse video of ebbing tide shows them nicely.

http://www.flickr.com/photos/suraky/4230976574/
Course facilitators and critics are unsettled about the increasing drop-out rate in MOOCs. Being far from active this time myself, I want to share my speculations about the reason for this.
I think the main point for abundance is that it may foster diversity. Under certain preconditions, it offers the best chance to generate a true, authentic, random statistical kind of diversity which can finally lead to a representative, exemplary breadth of learning, because is destroys the illusion that one could still gain some comprehensive core knowledge, or some unbiased curated selection.
Can lacking massiveness be somehow compensated? For example, can the consequential lack of participants’ diversity be compensated by a diversity of resources? I doubt this.
Responding to Rita Kop who said in a comment at Tony Bates’ blog:
“Perhaps the decision to leave out the learning management system from the Change MOOC has not been a wise one”.
I once supported this decision and I still do.
Responding to Tony Bates’ question “Can universities or colleges change from within…”: I think, yes, All the most promising technological benefits that I can think of, leverage some new middle way/ in-between, some new gradual possibility, or some new mixture/ combination — that are all well compatible with incremental embracing.
Due to heavy spam fire, I accidently marked too many comments as spam. If these commenters should have problems with new comments, please tell me!
Navigation in the long, ramified discussion threads is a big challenge. Traditional web pages usually offer a left navigation pane for this task where it is hardly possible to visualize the hierarchically nested connections, let alone the more sophistcated cross links that are typical for connectivist activities. In short, they are nodes-oriented rather than connection-oriented. In an alternative approach, the connections have more room than the single node (or in graph theory terms: the edges are more prominent than the vertices). This should fit better for connectivism, which emphasises connections over nodes and reminds us that traversing the links helps with learning, right?
It is a good idea that this new MOOC starts with a week for setup and testing, such as feed registration, OPML feed list assembly and “Hello World” testing messages.
IMHO, the unique “selling point” of Connectivism is its powerful metaphor that applies to the three layers neuronal, conceptual, and social/ external.
For me, asynchronous participation is probably the single greatest affordance of networked learning, because it offers a unique combination of features that were previously never possible simultaneously: slow reflection like when reading a book, and quick reactivity, almost like in oral exchanges. In Plenk, there were different options available.
I don’t duck out of the inevitable D-I-K (-W) definition started in the forums. But more interesting than a single definition of knowledge, are the new distinctions of knowledge types that are afforded by connectivist notions, and the distinct usages of the terms. So, managing/ dealing with/ traversing pieces of information might well be called knowledge management because it generates or grows knowledge.
I think the biggest problem for connectivist PKM environments is the omnipresent incline towards premature pigeonholing of stuff into folders. The relational structure is still the step-brother of the hierarchical structure, because it still lacks the visual modality.
Why (not) want new tools? The forums discussion reveals a reluctance against ever more new tools. We are overwhelmed already. We cannot keep up with them, but we can pick our choice. And once we engage more thoroughly with our favorite tools, we will discover what functionality and usability they are missing.
Seemingly, for each conceivable purpose and preference, there is a tool that exists. This might be true for the communication and collaboration purposes on the social or person-to-person level of connectivism, but not for its conceptual level. Just consider such a simple thing as drawing a connection line between two items in your folders on your hard drive. This was discussed in a paper for PKM2010 and demonstrated with a prototype.
Filtering may be the most crucial Critical Literacy for modern learners. Will Richardson listed it right after “1. Pursue your passion” and “2. Read widely”. which I interprete as 1. depth and 2. breadth — the irreconcilable ideals. Picking and filtering can, in a way, reconcile them.
I like Stephens’s notion that tests are used as proxies. It is consistent with the notion that learning works indirectly, by induction rather than by transmission.
My “theory”: Many educators won’t admit to themselves that their own cognitive style is not the only best one that leads to the most effective learning. So naturally, there are problems to reconcile some students’ real learning processes with the predicted progress. And therefore, ever new theories are needed.
“Connects knowledge” sounds good (upper left quadrant of slide 12 of Wheeler’s presentation). But does this equate to connective knowledge as in Connectivism? I think it is just “snap-in” knowledge that needs to be “augmented” by connective knowledge
Jenny mentioned that the process we worked through for our paper, was not open to all. At least, it can be made a little more transparent here.
Apparently, the main difference between PLE and LMS is centrality of the LMS. But a typical LMS shows more than forums-like centrality. It is often a centralistic mindset that reigns here. the choice between PLE and centralistic LMS is a matter of preference and mindset, just as well as the choice between blogs and central forums. But while the forums choice depends on the styles of the students, the LMS usage is often influenced by an unaware preference of the teacher.
I am not content with my understanding of PLN vs. PLE unless I see in in a picture. Here is my attempt:
Some blame the mass market for underachieving user interfaces. In my opinion, there is nothing wrong with mass-oriented usability. However, the idea that one optimized interface is optimal for all the mass of users (one size fits all) ignores the fact that there are several cognitive styles, each of which would constitute a separate mass market of its own.
Currently I am participating in a German online course that is conducted within a closed group. I am surprised how much I dislike this, and how I miss much of the openness of CCK08.
Much has improved on bikeway signposts. Finally, the mainly work as expected in a network. But it is interesting to observe that a network is not necessarily perceived a network from the beginning.
Responding to John and Heli, by quoting crucial passages of Stephen’s explanation.
Stephen disagrees with George about the contiguity of the neuro networks in our minds, with the networks of people/ ideas/ things in the external world. The expression, for example, “the outboard brain”, suggests this continuity. Frankly, the outboard brain, and also the contiguity made sense to me, because I have not yet had patience for the philosophical true distinctions.
In a connectivist course it seems to be important that the learner is able to connect a weekly topic to the main course topic.
Similarly like “literacy” is much more than reading and writing, the “critical literacies” required for the internet citizen, are connotated with much more than the critical evaluation of the truth of assertions. Like reading and writing were associated with generally superior intellectual capabilities, the skill of filtering true information is strongly related to more general skills of coping with the abundance, and filtering, and picking the gems.
Windows 7 repeatedly jumbled my desktop icons. The desktop was the last folder where I could arrange my icons freely, while in all other folders, Snap to Grid is now mandatory. Why do they prohibit me from using my folder windows at least a little bit like a mindmapping tool by rearranging and clustering the icons in a spatially meaningful way?
Today I learned what "Ligne Claire" is: the drawing style of Tintin. I think this style disproves the prejudice that comic strips were inferior. Unlike other, more distance-less styles, it does not suggest the reader how they should feel about the story or the characters shown, but rather, enables them to develop their own stance while reading and viewing.
Prezi had the potential to overcome the suffocating linearity of traditional presentations. But unfortunately, it is often used for merely a new, gimmick, slide transition effect.
A new German paper “Views on the comment culture of weblogs” finds that the hope for a comment culture, the reflective element of participative learning, has not yet been fulfilled, and that weblogs are rather monological and only few threads are emerging.
why are Web2.0 affordances not embraced for scholarly communication? A new report from UC Berkeley gives a shattering answer and a discouraging advice to young scholars. Perhaps there is hope that older scholars and elite universities can be more broad-minded?
In a new article on Learning Styles, the old black and white thinking is reiterated: Approaches are wrong because there is no evidence. But also critics with more differentiated views have their say, who advise teachers “to become aware of their own learning style”.
A new German publication dissects The deployment of Web 2.0 for teaching. A significant argument is that active students are always a minority. I think this is true when diversity and breadth of knowledge is mistaken for plain mass of content.
I am always keen to learn about Scrapers who allow excerpting structured XML data from “almost” structured HTML. Unfortunately, I haven’t yet found one who is robust enough against small irregularities.
Yesterday’s OLDaily questions “core knowledge”, and I am trying to guess the tacit discomfort behind this misguided idea: Blinkered specialists vs. broad knowledge, shallow generalists vs. deep knowledge, indirect side effects vs. measurable memorization of facts, absurd amount of useless facts vs. exemplary drill-down on diverse topics.
I had the chance to submit my latest dreams about tomorrow’s mindmapping. And on the other hand, I was disillusioned about its deployment in today’s academia.
Lisa Lane has a great advice for the unnecessarily intimidated among faculty: Playing around with online tools oneself, but not getting enchanted by the tools.
After returning from vacation, I noticed how quickly I skimmed my RSS reader, and this alarmed me. If an item does not resonate with me immediately, it could also mean that I just don’t understand its context quickly enough.
While many visualization tools focus on the output side (on the impressing presentations), I am again looking for the optimal tool for the input of connected ideas. I wonder if the crucial limitations can be removed by more zooming, or by some “spread”.
While both bloggers and forum lovers on CCK08 value diverse, non-linear, “big picture” style conversations, there might be subtle differences in the type of conceptual connections that both camps feel most comfortable with. This differences affect the “closeness” or “nearness” of the concepts, ideas, and aspects under discussion, both “spatially” and temporally.
In a new essay on domain-generality or domain-specifity of creativity, R. Sternberg emphasizes the individual’s decision, attitude, mindset, to use their differing skills, abilities, resources. The decision attitude is described as investment. My own thoughts about this involve the attitude of note-taking.
George Siemens asks “What can visuals do that text can’t?”, and Dave Gray just presented such a visual about text that answers the question.
Never before I have seen such a vivid visualization of the concept of “facts” as in the Flickr set “Free the Facts”. It employs some simplification but I think it is legitimate and credible.
Never before I have seen such a vivid visualization of the concept of “facts” as in the Flickr set “Free the Facts”. It employs some simplification but I think it is legitimate and credible.
“WissensWert” is running a blog carnival. I tried to answer their questions.
“Courseocentrism” impedes the development of critical thinking skills; only the high achieving minority of students are able to synthesize the disparate views on their own, while the struggling majority are confused by the “mixed messages” they get from their different teachers. But I doubt that harmonized content would help much, instead of growing the connections on their own.
Stephen Kosslyn describes an approach of studying a “periodic table of the mind”. I like the chemical metaphor which prompted me to think about modern alchemy.
Cleaning up my repositories, showed me that my bookmark collection has lost much of its relevance. If the links aren’t digested right away, they won’t be useful later, either. Read more about my filing and cleanup strategies.
Do “creative chaotics” prefer bulky email newsletters over frequent blog posts? There are very different attitudes towards daily habits and long, impressive, linear post collections.
Trying to make meaning of George Siemens’ “Connectivist Taxonomy”, I ended up with a tilted structure resembling the Southwest German Cuesta landscape.
Before I put this unique course aside, I want to mention some workflow-related things, reflect about the proof of concept to crossbreed topic coverage and free-ranging methods, and marvel at the magic to model and demonstrate diversity all alone.
I think the most urgent research need in Connectivism is not to gain still more insights but to develop a conceptual arsenal, or toolbox, for expressing and proving these findings.
As my final presentation, I uploaded a 2 minute Flash file (no audio, 4.5 MB). It answers the question “How has this course influenced my view of the process of learning” and is a reduced, visually enhanced version of my yesterday’s posting about the relationship between conceptual and social/ external connections.
As an assignment of Week 11, here is my final Cmap.
The most intriguing question of this course was the relationship of the social/ external and the conceptual level of connectivism. It becomes apparent in Fuzzy categories, Structural preferences, Echo and resonating, and Knowledge residing externally.
Why is it so difficult to change the practice of education? Because learning mechanisms involve subtle differences that are at odds with the binary thinking in terms of either correct or incorrect of education leaders.
I am still struggling with the role of openness in connectivism. Is it a prescriptive, integral part of the theory? There are many possible reasons why people would prefer some privacy zone for their learning. And I do not yet understand how this would prevent growing connectivist connections on the conceptual level.
A new version of my favorite think tool has finally been released.
Many speculations about the different participation styles and about a possible “failing” of the CCK08 course have been written. I don’t see a “failing”, and here is why.
Short Paper for week 5 - 8. “Take this opportunity to enjoy a creative stroll in rethinking ‘what could be’”.
Traditional assessments and citations alike, are flawed in the context of connective knowledge. I think a possible reason is that validity assurance is overly messed up with prestige-laden ranking considerations.
Traditional assessments and citations alike, are flawed in the context of connective knowledge. I think a possible reason is that validity assurance is overly messed up with prestige-laden ranking considerations.
In one of my favorite children’s books, information technology in the classroom of 1961 plays a prominent role.
Studying as a preparation for a career in a complex future, is often contrasted to the ideal of education in its own ends. Humboldt’s rather modern ideas have been explained in a presentation this month in Zürich.
This week’s topics of complexity and chaos seemingly suggest ready-made recipes for next week’s topic of instructional design: Let the students rehearse complexity right away. But there may be a fallacy.
The concept of “lubrication” of this week’s readings explains why the internet may be over-emphasized in our lives. Similarly, the internet/ social/ external layer of connections and knowledge was overemphasized in our discussion, as oppposed to the conceptual layer. I think this is because we are trying to equate the two types of knowledge rather than seeing the unifying pattern.
If I were forced to post at least once a week, I would be in trouble this time. I could only highlight what I liked the most: The “walls - bridges” contrast and the “sameness - affinity” polarity.
The address bar of the browser is more and more devaluated. In IE8 beta 2, a delete icon is right where I usually click.
One assignment of week 4 was to upload my concept map. Here it is.
My emphasis would have been much different, at least about the relevance of gopher.
I think, the concept of theory is distracting; it is a vulnerability that it looks like a Grand Unifying Theory. Its strength is the single neural metaphor.
I think there is no need for a single theory covering Neural, Conceptual, and Social/ External layer. The interaction between conceptual level and social/ external level connections is already interesting enough.
In a broader sense, I would call every mesh-like diagram of concepts a Cmap and ignore the urge for “propositions”.
I am particularly fascinated about how this social level interacts with the conceptual level through mechanisms like “People who read this also read that“. And the tree vs. web dichotomy has intrigued me ever since my very first blog post.
The CCK08 moodle forum is a challenge. Both the nodes and the connections of the mammoth threads are impossible to overlook. The connections to the previous posts are mostly implicit, or at best cryptic (”Hi Pat”), so that reconstructing them costs me thorough reading rather than scanning.
Often “What is?” definitions ambitiously try to describe deeper meanings. But even the ordinary language meaning of “knowledge” is already interesting enough in the light of today’s changes.
The problem with the status of a theory is that its descriptive power is often immediately intertwined with prescriptive claims.
My way of approaching the confusing landscape of countless tools, sites, and resources, was to try and get a visual overview.
The idea of connective knowledge struck a chord with me since networks have been important to me on many levels.
There is an interesting discussion going on about Dave Gray’s “Marks and Meaning” (an “unbook”). My argument was: Some visual thinking techniques that are very much optimized for the “selling your ideas” stage, IMO, impede the thinking stage. Particularly: Prematurely grouping things into a hierarchical, tree structure if they need a complex web structure. Dave’s great reply pointed to “where the art comes in” and to “the social evolution of diagrams”.
In the upcoming “Connectivism &amp; Connective Knowledge” Course, the first week’s topic asks “What is Connectivism?”. I am not so comfortable with a fixed definition. Furthermore, I think its most interesting aspects are not only being a theory of learning, but offering a whole new view for much more. And all of these aspects have in common that they can be illustrated by the neural metaphor.
The metaphor of the “horseless carriage”, showing how new technology often just emulates previous practice, is still particularly valid with tools for studying or thinking.
My little experiment gradually transforms a mindmap, by rearranging the topics such that the long-distance associations become closer. Watch the differnce…
When online resources are optimized for print, it is often a pain to scan them to decide whether to print them or not.
A great position paper has been published on the future of teaching. It deals severly with central institutions of higher-education pedagogy
I have the impression that more and more new blogs content themselves with passing on news without adding value. And readers oversubscribe. Obviously, two different styles are now at work.
A German paper titled “Is there a Net Generation?” has sobering findings about the transfer of IT competencies to learning.
Finally, the promising think tool Deepamehta installs with a doubleclick on a simple XP machine, and so I can at last recommend to try it out.
I think that text markup for better readability belongs to new media literacy. Therefore I searched curriculums for guidelines. But these address only artistic aspects.
Guidelines for scholarly writing abound, but often they disregard the macro markup necessary for speed-reading, or skimming.
A fascinating paper by Bret Victor provides an excellent analysis, and a debatable conclusion; That interactive elements are inappropriately used in information design, and that they should be reduced. I agree that they are not ideal BEFORE presentation of data but still have a great potential for knowledge work AFTER page loading.
A new German book on Methods for the Personal Knowledge Management was published. For me, it does not work. I have the impression that all the analytical dissections and definitions are somehow mincing, or missing, some of the most challenging problems that exist for a knowledge worker. But if you understand German, you should definitely obtain this thought-provoking book.
The impressive list of “67 ways to tame the procrastination beast” quickly shrinks to a few central ideas, and I have my doubts about them. Especially the advice to break the whole into smaller, manageable parts, conflicts with an important strength of many procrastinators: to keep sight of wide contexts.
In “Kosslyn, Clear and to the Point”, most of the recommendations were immediately plausible to me, whereas a few guidelines got me thinking about whether they would be applicable to educational powerpoints. But eventually, this problem leads to the question which sort of matter should, at all, be canned into the “get across” transport container of a presentation monologue.
My favorite set of PIM tools was severely challenged lately, and while fiddling about with alternatives, I realized which properties are indispensable for me: good connector lines manipulation.
Teaching done by researchers is often messy, but it brings about a positive effect of informal learning: to cope with the lacking scaffold and structure, the students have to become very autonomous, and they learn how to learn in a very self-directed way.
After moving to Vista, I desparately miss the “Up” button in all folder windows. I welcome the many new affordances of tagging and improved searching. They would perfectly SUPPLEMENT the file hierarchy. But they should not try to REPLACE the sense of hierarchical structure.
Many bloggers have listed their Top Ten Tools. Here is my list. It mainly consists of very basic tools, and I use them often for other purposes than the standard ones.
For syncing my office and home materials, I use a very primitive method, but it preserves me a sense of space, and it helps me keeping a work-life balance.
I will NOT use DeepaMehta as my main notes tool. After long attempts I ended up without the integration of text and visual connections that I had dreamt of, with Wordpress for the text portion and manually synched powerpoint visualizations. And occasionally, as “the cherry on the cake”, I use DeepaMehta, when a category of my private Wordpress has become too populated, to help gaining structure.
If a think tool is supposed to help with the very early stage of arranging one’s thoughts and notes, there are very subtle effects becoming very relevant. I experimented with a tool that uniquely integrates text and visual connections.
C. Quinn and H. Jarche have one word on learning styles: “rubbish”. I do NOT agree. Style is often confused with ability, and teachers and researchers don’t admit to themselves that they also belong to one or another style.
I am very unhappy with the change of my newspaper’s format to tabloid. I try to express what subtly frustrates me.
Recently, there was a rapidly increased search activity for “usability2.0″. Some of the hits refer to the usability that belongs to web 2.0, while others focus on cognitive styles.
It is amazing how much we have internalized certain restrictions of familiar desktop applications. If these restrictions are relieved, new usability challenges arise.
In a recent podcast, an extraordinary think-tool project was labelled maverick and esoteric. I think we still have not learned to embrace cognitive diversity.
In an interesting discussion between G. Siemens and S. Downes, they are addressing “knowledge elements”, concepts, nodes in the network, and entities. I am trying to understand the issues by looking at the “ports” of the network nodes.
Resource descriptions are not the adequate approach for supporting human learning and knowledge. But there are also people working on more humanized RDF approaches.
Another chapter of my Supplement to a student’s handbook has been translated.
 I wrote it in 2003 for a first year student when I found that the available student’s handbooks on “studying made easier” covered the computer merely as a word processor and literature retrieval tool. So I assembled some notes on how to use it as a think tool.
Stephen Downes’ contribution to the Online Connectivism Conference makes it clear why it is so futile to try to treat the patterns of complex cognitive structures as (complicated) rules. A severe example was our orthographic reform.
T. Buzan impressively argues that straight lines in mindmaps are too rigid. Most of the visualization methods in the recently published periodic table are rigid. Why is that and what can be done?
In this Part 2, I compiled some concrete examples. I grouped the various tools and work-arounds I have experimented with, by their inclination towards the three modalities. The center is empty.
Not prematurely publishing RESULTS, but collaboratively reflecting the QUESTIONS, might help developping new theories.
“Different people seem to have different levels of task switching that is tolerable or even enjoyable.” And these different people exhibit very different styles of multitasking, some of which seem plausible to me.
For user interfaces navigation, D. Berry distinguishes two paradigms: “go to” and “bring to me”. Which of these is the background for IE7 abolishing the old flyout favorites menu from the default settings, in favor of the favorites side bar? Apparently the side bar is supposed to be more “bring to me”, but when actually working with IE7, it is really just the annoying opposite.
Finally, we have a campus-wide blog server that can be used by any of our users with their normal account. So I can also move from my old blog site whose hand-made XML was not accepted by some clients (although it was validated correct syntax). If you still encounter problems please tell me.
The biggest challenge for a think-tool is to accommodate all three possible shapes, or modalities, that conceptual connections may adopt: Visual, verbal, and virtual.
Do we need one think tool for everyone and everthing (standard), or are many different tools better (personalization) ?
This (German) Guide is supposed to complement a detailed study guide with some tips for using the personal computer as a tool for thinking support …
This German text from Uni Dortmund contains useful thoughts about link figuration …
Intra-textual links increase distracting “referential navigation”, and this, in turn, reduces orientation …
The HyTex project asked challenging questions: what precisely are the most important differences between text and hypertext? …
Again experimenting with hierarchical arrangement of index words. This time, I used the hierarchy for prioritizing the hyperlinks …
J. Souttar’s great essay shows aspects from philosophy, history, and design, regarding context-less, atomized content …
Looking at word roots, an interesting observation can be made: “multimedial” subject groups are over-represented …
“The alphabet is a funnel”, says R. Horn - in his visual language, of course.
Here is a small Javascript sample exercise….
Experimenting with (poly-)hierarchical arrangement of word lists from the etymological dictionary …
Unsystematic, inconsistent link marking, linking structure, link selection, and poor text presentation design could be overcome by borrowing from hypertext elements and visualizations …
Alphabetical encyclopaedias are not tuned for context, even after the practical compulsion of the sort order for the print versions no longer apply…
Multimedia “grammar” could use the hyperlink as the verb, and the link type (hierarchical or cross-reference) as the gender of verb….
The main reason why Hypertext has a fascination on me since a long time, is probably the fact that it acts as a bridge between two basic, opposite, and complementing elements that may be called gender of knowledge representation: tree and shortcut…
What data structures do humans think in? What data types should be supported by a cognitively adequate PKM tool?
An interesting study identifies a type of academic homepages as sycophants, mainly because they link back to their departments. It is true that there are problems with these pages but IMO they are different.
A difference between object visualizers and spatial visualizers has been discovered. What does that mean for personal information management techniques?
Reading is antisocial, but writing is first and foremost about creating a community of writers ?
How would the “library 2.0″ look like? Users’ tags for emerging knowledge, librarians’ classifications for older, settled knowledge?
In his inspiring article on “The Joys of Shallow Thinking…”, G. Siemens notes the insecurity of education about how deep or shallow learning should be. I do think that deep learning of a topic is necessary, but not in its own right but as a sample or representative for the similar topics that, later on, can be touched more shallowly.
How much work should the RSS aggregator do for me? Should it try to group the various feeds by some sort of context such as authors’ topics or tags, or by day, or by geographical location? No, just count and perhaps cache them.
D. Pollard pointed to the impressive ecolanguage.net that applies animated symbols to explain relationships. L. Arnold makes them especially powerful by leveraging techniques such as zoom, aggregation, and expanding / collapsing.
In her Cognitive analysis of tagging, Rashmi Sinha hits the core problem when she points to our fear that we would make a wrong categorization decision. “We need to consider the overall categorical scheme.” I think this fear can be mitigated when using cross reference links.
Stimulated by D. Grey’s detailed posting “On the concept of a concept”, I tried to depict my view of concepts.
It is amazing how often it is useful to follow a detour when using desktop application tools in daily PKM tasks. Normally we assume that solving IT problems involves some steps along a click path where each click takes us closer to the target. In some cases, however, the first step does just the opposite. These cases require a different attitude towards IT tools: sense of orientation and overlook rather than task-driven just-in-time skills.
Collaborative library (ColLib, via S. Downes) sounded very promising to me, since I am hoping for the peaceful coexistence of amateur tagging and professional classification that C. Shirky denies (Aug. 27th). His most plausible argument ist cost: Tagging is cheap. But for whom is tagging cheap? For the providers of the tags - okay. But for the consumers?
In his great article from last week about Making Knowledge, D. Grey said many deep details holding true for everybody (regardless of individual cognitive styles), much more than I considered possible, probably everything that can possibly be said about this topic, the ultimate general description.
“How can visualisations aid thinking?” This was the central question at a small symposium on Think Tools last weekend. IMO, they can probably relieve a certain constraint which one might identify to constrict thinking.
Finally I had a chance to see Deepa Mehta in action, the Semantic Desktop System whose description I recently reviewed.
On my this year’s bicycle tour, I learned a lot about the relationship between navigation in the virtual vs. real world: I discovered another reason for the continuous annoyance with bicycle path signposting. And I became more aware about the problems of zooming on virtual as opposed to real geographical maps.
Despite of vacation, a quick link to yet another great idea of M. Böttger. She suggests (in German) a differential psychology approach for studying the filing behavior of people.
Annotation is a central topic for shared spaces, but unfortunately it is still a stepchild and suffering from many small silly technical problems.
There are many learning/ personality styles inventories out there, but what seems still missing are profiles for personal information management styles.
Interesting ideas about “think-tools” are offered by the authors of Deepamehta.
Our university library is starting off into a new era of Open Access and RSS Syndication, categorized by Dewey. Here is the RSS-Link of the ten most recent self-archival publications, and if you have an aggregator similar like mine (see the 146 kB screenshot), you can sort them by DCC just clicking on the heading of the subject column. I think this is a pretty promising approach, which might soon combine both the capabilities of smart aggregator filters of the users and professional cataloguing by LIS staff.
The difference between Mindmaps and Concept Maps is still confusing. I think Concept Maps can be compared with literacy, while Mindmaps are more “oral”.
Useful arguments that may help to overcome a major personal information management problem.
“The end of the written word”, this is much food for thought.
I assembled a little statistic of my previous postings. In 43 postings, I linked 82 times to 69 other blogs or pages, which belonged to 49 people. Of the 8 blogs I linked multiple times, 3 are female, 4 are male, and 1 mixed (M2M). Of the 37 links going to these, 18 went to women, and 19 to men. My blog map does not reveal a clear structure. Only that I like to link several times to the same posting, perhaps to link the same thoughts together in different contexts.
Many people use presentations which many people don’t like and which don’t leverage the potential of modern programs. But they are a compromise of two opposite styles.
Why consuming information is different from eating chocolate and borrowing eggs.
Why discussions via blogs are different from those on mailing lists and forums.
Knowledge technology is now ready for emancipation from single-tracked, excessive textualization, but IP policy is not!
The debate about D. Grey’s “Personal Learning” post and G. Siemens’ comment intrigues me.
About “feed overload/intimidation syndrome” and feed selection habits.
Here is yet another teacher’s account describing his efforts to involve people in blog discussions, to balance participation, “to activate the long tail”. I think, when people are urged or even mandated to blog, the novel phenomenon is thoroughly misrecognized.
Last week I learned about a cognitive styles difference that I had not known before: “Radial” vs. “Cartesian” (M2M). While the latter is more absolutely oriented, the former focusses on relative, incremental, change. The incremental, preliminary characteristics, the revisability and rearrangeability is very important for me.
I have described now quite a lot of my tool-using habits, but have yet to conclude this by covering the basic desktop usage.
Many bloggers described their use cases where they prefer paper and pencil to keyboard and mouse. I often use a primitive tool that emulates paper’s immediacy affordance best.
Many bloggers have discussed the difference of “data”, “information”, and “knowledge”. Here is my attempt …
Description of a visualization technique usage scenario which could be much more effective with improved tools.
D. Grey explains concept maps vs. mind maps and shows examples. As often, I find the mind map more appealing and creatively stimulating than the other example, although it is a restricted tree structure. Why is that? I experimented with several versions and considered the Boettger distance.
Blogging is not urgent but important. Same applies to blog listening which is the competitive advantage of the weblog world. It’s more about “just in case” knowledge than “just in time” knowledge. It may not be everybody’s taste, therefore. If problem-solving is one’s direct and main focus of KM, bloggers’ evangelism will probably not convince them. But there is a growing discomfort with the “neat, clean and often sterilized understanding of problem solving”.
In the stone-age of the Web, I was a supporter of the Virtual Library, or its predecessors, like the EuroGopher Subject Tree, where I incidentally became the maintainer of the History branch (see details in a German newspaper article). I helped with the general German resources catalog, and the history trees on worldwide and national level. I still have a lot of sympathy for the project, since I do not hate trees and hierarchies (as long as they are made sufferable by reasonable “see-also” cross references). Therefore, here are some thoughts how the VL might relate to RSS, Topic Maps, and folksonomies.
My preferred note-taking technique is not efficient enough for taking notes during oral conversations but only for excerpting literal artefacts (which is a pity since I learned yesterday that the oral side of the cultural divide is the more important one).
After reading M. Lessard’s “Expression et transformation de la connaissance” in today’s Zero Seconde, Kleist (1777-1811, “Über die allmähliche Verfertigung der Gedanken beim Reden”) would perhaps have written a comment “On the Gradual Production of Thoughts Whilst Blogging” into his blog. See also chapter 1.1 in this PDF.
In corporate intranet blogging, the novel information flow is IMO more convincing than the conversation aspect. The respective roles of both can be illustrated by comparing the blog to pinball.
Magdalena Boettger depicts the difference between personal and organzational KM as plausibly as I have never seen it before: using a continuum along a dimension of growing interpersonal and intertemporal distance.
Great debate on loose vs. controlled vocabularies. But can two cognitive styles be debated? Knowledge management, IMO, needs to accommodate them both.
Stimulated by L. Efimova’s thoughts about personal categories and D. Pollard’s report about his getting-things-done experience, I decided to write down what my personal categorization strategy looks like. 

To summarize: Without shortcut links, I would be lost. Using them allows me to rest on fairly deep and fairly long-term filing categories.
Traces of knowledge construction made visible.
Interesting new links on mapping of knowledge structures…
Mathemagenic about binary thinking….
According to the “information foraging theory” quoted by Infovis, we are hunter-gatherers for information prey….
Learning Object Metadata entered by one user type can be leveraged as recommendations for users of similar type (”neigborhood users”).
A blog discussion is going on about the terminology of “Knowledge Worker” (M. Röll). For me, the main connotation is: a very normal, ordinary occupation.
Digital generation needs “Multi-threaded stream of discourse” rather than neatly pre-packed content.
OLS (Open Learning Support) presented by D. Wiley at USU ITI conference.
There is nothing magic with the hyperlink except that it intensifies the magic of the ordinary paper reference pointer …
Bold, italics, and underline each fulfill a distinct role, and underline is ideal to indicate all kinds of relationships or links. But unfortunately, underline is underused. Why is it so unpopular? Perhaps because it is the markup of teachers.
“Getting Real” offers striking, plausible recommendations for building successful software. Several of their arguments would also support the idea that usable apps should cater to cognitive styles.
A today’s newspaper article complains about the current financial promotion policy that divides universities into those with research and those that merely serve a cost-effective (i. e. lowbrow) training. It causes thinking about the underlying concept of learning and knowledge.
Explaining blogs or other collaboration/ personal productivity tools is not easy. Often, they are a mixture of similar ones. Here is my attempt.
My attempt to answer this interesting question. A few reasons are specific to collaboration, but the major reasons are also applicable to other, personal productivity tools: the new subtle distinctions are hidden by overdone integration.
In her keynote speech at GMW06, G. Reinmann identified an innovation throttle of educational research: Methodological Monoculture.
Thanks to N. McKeand I have downloaded “Folder Marker”, and with minimal extra effort I can even assign infotip labels to my folders.
Jack pointed to a test for assessing one’s own innovation style, and he values the mutual awareness of styles. I wonder how this applies to the relationship between consultants and their clients.
There is an interesting discussion going on about whether we need a new term for blogs in order to “sell” them to non-believers. I think we should not try to sell them to everybody.
I am glad to see that there are more and more approaches considering the relationship between cognitive styles and software user interfaces. But still it is a long way to go.
Musing about the usability of the signposting, I found another example where forced narrow context annoys me.
Finally, my most-clicked text is translated. It shows how to use graphics and database programs to reorder, rearrange, and visualize concepts in an easy way, for instance, with simple elbow connectors for hierarchical relationships, and curved connectors for cross-reference relationships.
In an earlier posting on Usability 2.0 I complained that user interfaces don’t yet cater to cognitive styles. Now it seems that Office 2007 and Vista do exactly this in a decisive, courageous way. They take sides for one type of users that can roughly be referred to as left-brainers: focussed on a narrow context.
The “cognitive styles” underlying the preferences with IT tool usage have intrigued me since long. Finally I read about theories with some plausible concepts and tried to apply them to my observations. Some people just don’t like to expand/ collapse details near the border of a topic, click on stand-in’s for distant ideas, or smoothly zoom out and in from narrow contexts to wider contexts and back, but they prefer to hide everything not immediately relevant and make the focussed current context as comfortable as possible.
Some usability strategies suggest that the IT entities, such as folders and applications, should be hidden in favor of the user’s semantic entities, and that a stable, focussed context should be maintained. I agree only partially.
After struggling for many days, I found out what made me hesitate to follow the intended approach for migrating to a personal wiki, and so I won’t split my existing Notepad files of assembled tiny notes.
Jack’s ongoing struggle with selecting a suitable RSS reader, is symptomatic for the outdated usability objectives of many software products. Blog reader software is particularly sensitive to different cognitive styles, since blogs are a fine-balanced hybrid between email postings and personal web pages.
Jack’s ongoing struggle with selecting a suitable RSS reader, is symptomatic for the outdated usability objectives of many software products. Blog reader software is particularly sensitive to different cognitive styles, since blogs are a fine-balanced hybrid between email postings and personal web pages.
Since I am bad at inventing search words, my referer logs have an additional value for me: I can imitate them and find gems.
K. Egan’s 1997 book “The Educated Mind. How Cognitive Tools Shape Our Understanding” offers great insights about tools like oral language and literacy.
Meta-data and person to person connections
 Another great post by D. Grey, about how meta-data can enhance collections/ content by means of connections/ context.
I hate corporate homepages where the company’s acronym is not explained.
In his “Connectivism Taxonomy”, G. Siemens enumerates various stages of learning, and he positions Contribution and involvement before Pattern recognition. This did not convince me at once.
When we need to communicate something important to our bosses, the mix of graphics, written words and oral narration must be very well balanced.
I won’t like IE7’s feed reader and will stick to my dedicated aggregator newzcrawler that rather resembles an email reader than a browser. Is it my backwardness, or my “accent” as a “digital immigrant” from the ancient land of email-centrism into the country of the “digital natives?” I think no, it’s preferences or cognitive styles.
It is amazing how meager the progress has been to leverage the human sense of 3D orientation for IT applications. The wide physical movements and rotations of one’s head and body are much easier to be remembered than the tiny fine-motorical mouse moves in our 19 inch 2D world. How could I leverage this physical orientation?
Usability “1.0″ has attempted to find the one optimized user interface, e. g. an ideal menu tree, or a perfect classification of items. The next generation usability has learned from the users of the read/write Web 2.0 that there are alternate usage profiles, and it acknowledges that there are different cognitive styles.
Approx. 130 web pages, linked to from 62 blog postings, tagged with 95 combinations of 51 del.icio.us bookmarks, plotted in a diagram, make up an impressive visualization of thought connections.
